name: capnotrainer_sdk
description: A Flutter SDK for CapnoTrainer
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus : ^1.25.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

